# exampleSite/config.yaml
baseURL: https://bruh.wiki/ # Replace with your domain
languageCode: en-us
theme: smigle
title: andrew's blog
menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 3
    - identifier: about
      name: About
      url: /about/
      weight: 4
params:
  abbrDateFmt: "Jan 2"
  author: "andrew vargas"
  brandIconFile: "images/atproto.svg"
  dateFmt: "2006-01-02"
  ##
  ## Options for overriding theme or page defaults
  ##
  #customStylesheets: # Use to override theme styles, like logo size
  #  - "css/custom.css"
  #readingSpeed: 600 # Use to set custom reading speed
  #readingSpeedMin: 25 # Use to set custom reading speed range
  #readingSpeedMax: 175 # Use to set custom reading speed range
  social:
    - name: Bluesky
      url: https://bsky.app/profile/bruh.wiki
    - name: Mastodon
      url: <a rel="me" href="https://mas.to/@vandr">Mastodon</a>
    - name: Letterboxd
      url: https://letterboxd.com/vandr/
    - name: Pixelfed
      url: https://pixelfed.social/vandr
  subtitle: "shower thoughts?"
